# Generated by Django 4.2.16 on 2024-11-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=30, verbose_name='')),
                ('apellido', models.CharField(max_length=30, verbose_name='')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='')),
                ('correo', models.EmailField(max_length=70, unique=True, verbose_name='')),
                ('usuario', models.CharField(max_length=50, unique=True, verbose_name='')),
                ('fecha_nacimiento', models.DateField(max_length=50, null=True, verbose_name='')),
                ('activo', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('tecnico', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
